const DEFAULT_ERROR = 500;
const VALIDATION_ERROR = 400;
const NOT_FOUND_ERROR = 404;
const CONFLICT_ERROR = 409;

module.exports = {
  DEFAULT_ERROR,
  VALIDATION_ERROR,
  NOT_FOUND_ERROR,
  CONFLICT_ERROR,
};
